import {useState,type ReactNode} from 'react'
import {Link,NavLink,Outlet,useNavigate} from 'react-router-dom'
import {LayoutDashboard,Package,Tags,ShoppingBag,Users,MessageSquare,LogOut,Menu,X,Pencil,Trash2,Eye,Plus,Wallet,Search,type LucideIcon} from 'lucide-react'
import * as svc from '../services'
import {useAuth} from '../context/Auth'
import {resetAllData} from '../data/store'
import {btn,ErrorState,formatPrice,Logo,Stars,useAsync} from '../components/ui'
const NAV:[string,string,LucideIcon,boolean][]=[['/admin','Дашборд',LayoutDashboard,true],['/admin/products','Товары',Package,false],['/admin/categories','Категории',Tags,false],['/admin/orders','Заказы',ShoppingBag,false],['/admin/users','Пользователи',Users,false],['/admin/reviews','Отзывы',MessageSquare,false]]
export function AdminLayout(){const[open,setOpen]=useState(false);const{session,logout}=useAuth();const nav=useNavigate()
const side=<nav className="flex flex-col gap-1 p-3">{NAV.map(([to,l,I,end])=><NavLink key={to} to={to} end={end} className={({isActive})=>`flex items-center gap-2 rounded-lg px-3 py-2 text-sm ${isActive?'bg-red-50 font-semibold text-brand':'text-neutral-600 hover:bg-neutral-50'}`}><I size={18}/>{l}</NavLink>)}<button onClick={()=>{logout();nav('/login')}} className="mt-4 flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-neutral-600 hover:bg-neutral-50"><LogOut size={18}/>Выйти</button></nav>
return <div className="min-h-screen bg-neutral-100 md:flex"><aside className="hidden w-56 shrink-0 border-r border-neutral-200 bg-white md:block"><div className="p-4"><Logo/></div>{side}</aside>
{open&&<div className="fixed inset-0 z-40 md:hidden"><div className="absolute inset-0 bg-black/40" onClick={()=>setOpen(false)}/><aside className="absolute inset-y-0 left-0 w-64 bg-white" onClick={()=>setOpen(false)}><div className="flex items-center justify-between p-4"><Logo/><X size={20}/></div>{side}</aside></div>}
<div className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-14 items-center gap-3 border-b border-neutral-200 bg-white px-4"><button className="md:hidden" aria-label="Меню" onClick={()=>setOpen(true)}><Menu/></button><span className="font-semibold">Админ-панель</span><div className="ml-auto flex items-center gap-4 text-sm text-neutral-500"><span className="hidden sm:inline">{session?.email}</span><Link to="/" className="hover:text-brand">В магазин</Link></div></header><main className="p-4 md:p-6"><Outlet/></main></div></div>}
function useData<R>(fn:()=>Promise<R>){const[v,setV]=useState(0);const s=useAsync(fn,[v]);return{...s,reload:()=>setV(x=>x+1)}}
function Ready<R>({s,children}:{s:{data?:R;error?:string;loading:boolean};children:(d:R)=>ReactNode}){return s.loading?<p className="py-10 text-center text-neutral-400">Загрузка…</p>:s.error||s.data===undefined?<ErrorState msg={s.error}/>:<>{children(s.data)}</>}
const Head=({title,action}:{title:string;action?:ReactNode})=><div className="mb-4 flex items-center justify-between gap-3"><h1 className="text-xl font-bold md:text-2xl">{title}</h1>{action}</div>
const Table=({head,children}:{head:string[];children:ReactNode})=><div className="overflow-x-auto rounded-xl border border-neutral-200 bg-white"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-neutral-200 bg-neutral-50 text-xs uppercase text-neutral-500"><tr>{head.map(h=><th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y divide-neutral-100">{children}</tbody></table></div>
const td='px-4 py-3'
const Modal=({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode})=><div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="dialog" aria-modal="true" aria-label={title}><div className="absolute inset-0 bg-black/40" onClick={onClose}/><div className="relative max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-xl bg-white p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">{title}</h2><button aria-label="Закрыть" onClick={onClose}><X size={18}/></button></div>{children}</div></div>
type F={k:string;label:string;type?:'text'|'number'|'textarea'|'select';opts?:[number,string][]}
function FormModal({title,fields,init,onSubmit,onClose}:{title:string;fields:F[];init:Record<string,string|number>;onSubmit:(v:Record<string,string>)=>Promise<unknown>;onClose:()=>void}){
const[v,setV]=useState<Record<string,string>>(Object.fromEntries(fields.map(f=>[f.k,String(init[f.k]??(f.type==='select'?f.opts?.[0]?.[0]:'')??'')])));const[err,setErr]=useState('')
const cls='w-full rounded-lg border border-neutral-300 px-3 py-2 text-sm outline-none focus:border-brand'
return <Modal title={title} onClose={onClose}><form className="space-y-3" onSubmit={async e=>{e.preventDefault();try{await onSubmit(v);onClose()}catch(x){setErr((x as Error).message)}}}>
{fields.map(f=><label key={f.k} className="block text-sm"><span className="mb-1 block text-neutral-600">{f.label}</span>{f.type==='textarea'?<textarea className={cls} rows={3} value={v[f.k]} onChange={e=>setV({...v,[f.k]:e.target.value})}/>:f.type==='select'?<select className={cls} value={v[f.k]} onChange={e=>setV({...v,[f.k]:e.target.value})}>{f.opts?.map(([id,l])=><option key={id} value={id}>{l}</option>)}</select>:<input required className={cls} type={f.type??'text'} min={f.type==='number'?0:undefined} value={v[f.k]} onChange={e=>setV({...v,[f.k]:e.target.value})}/>}</label>)}
{err&&<p role="alert" className="text-sm text-brand">{err}</p>}<div className="flex justify-end gap-2"><button type="button" className={btn.secondary} onClick={onClose}>Отмена</button><button className={btn.primary}>Сохранить</button></div></form></Modal>}
const Bars=({rows}:{rows:[string,number][]})=>{const m=Math.max(1,...rows.map(r=>r[1]));return <div className="space-y-2">{rows.map(([l,n])=><div key={l} className="text-xs"><div className="mb-0.5 flex justify-between"><span className="truncate">{l}</span><b>{n}</b></div><div className="h-2 rounded-full bg-neutral-100"><div className="h-full rounded-full bg-brand" style={{width:`${n*100/m}%`}}/></div></div>)}</div>}
const confirmDel=(t:string)=>window.confirm(`Удалить: ${t}?`)

export function Dashboard(){const s=useData(async()=>({p:await svc.getProducts(),c:await svc.getCategories(),u:await svc.getUsers(),o:await svc.getOrders(),r:await svc.getAllReviews()}))
return <Ready s={s}>{({p,c,u,o,r})=>{const rev=o.filter(x=>x.order.status!=='Cancelled').reduce((a,x)=>a+x.order.total_amount,0)
const st:Record<string,number>={};o.forEach(x=>{st[x.order.status]=(st[x.order.status]??0)+1});const sold:Record<string,number>={};o.forEach(x=>x.items.forEach(i=>{const n=i.product?.name??`#${i.product_id}`;sold[n]=(sold[n]??0)+i.quantity}))
const cards:[string,string|number,LucideIcon][]=[['Товары',p.length,Package],['Категории',c.length,Tags],['Пользователи',u.length,Users],['Заказы',o.length,ShoppingBag],['Выручка',formatPrice(rev),Wallet],['Отзывы',r.length,MessageSquare]]
return <><Head title="Дашборд" action={<button className={btn.secondary} title="Сбросить все данные до исходного SQL-набора (только демо)" onClick={()=>{if(window.confirm('Сбросить все демо-данные (включая регистрации и сессию) до исходного SQL-набора?')){resetAllData();location.assign(import.meta.env.BASE_URL)}}}>Сбросить демо-данные</button>}/><div className="grid grid-cols-2 gap-3 lg:grid-cols-3 xl:grid-cols-6">{cards.map(([l,v,I])=><div key={l} className="rounded-xl border border-neutral-200 bg-white p-4"><I size={18} className="text-brand"/><div className="mt-2 truncate text-xl font-bold">{v}</div><div className="text-xs text-neutral-500">{l}</div></div>)}</div>
<div className="mt-5 grid gap-4 lg:grid-cols-3">{([['Заказы по статусам',Object.entries(st)],['Топ товаров (шт.)',Object.entries(sold).sort((a,b)=>b[1]-a[1]).slice(0,5)],['Оценки отзывов',[5,4,3,2,1].map((n):[string,number]=>[`${n} ★`,r.filter(x=>x.rating===n).length])]] as [string,[string,number][]][]).map(([t,rows])=><section key={t} className="rounded-xl border border-neutral-200 bg-white p-4"><h2 className="mb-3 text-sm font-semibold">{t}</h2><Bars rows={rows}/></section>)}</div></>}}</Ready>}

export function AdminProducts(){const s=useData(async()=>({p:await svc.getProducts(),c:await svc.getCategories()}));const[ed,setEd]=useState<{id?:number;init:Record<string,string|number>}|null>(null);const[err,setErr]=useState('')
return <Ready s={s}>{({p,c})=>{const fields:F[]=[{k:'name',label:'Название'},{k:'description',label:'Описание',type:'textarea'},{k:'price',label:'Цена, ₸',type:'number'},{k:'stock_quantity',label:'Остаток',type:'number'},{k:'category_id',label:'Категория',type:'select',opts:c.map(x=>[x.category_id,x.category_name])}]
return <><Head title="Товары" action={<button className={btn.primary} onClick={()=>setEd({init:{}})}><Plus size={16}/>Добавить товар</button>}/>{err&&<p role="alert" className="mb-3 rounded-lg bg-red-50 p-3 text-sm text-brand">{err}</p>}
<Table head={['ID','Товар','Категория','Цена','Остаток','Действия']}>{p.map(x=><tr key={x.product_id}><td className={td}>{x.product_id}</td><td className={`${td} font-medium`}>{x.name}</td><td className={td}>{c.find(k=>k.category_id===x.category_id)?.category_name}</td><td className={td}>{formatPrice(x.price)}</td><td className={td}>{x.stock_quantity}</td><td className={`${td} whitespace-nowrap`}><button aria-label={`Изменить ${x.name}`} className="mr-2 text-neutral-500 hover:text-brand" onClick={()=>setEd({id:x.product_id,init:{name:x.name,description:x.description??'',price:x.price,stock_quantity:x.stock_quantity,category_id:x.category_id}})}><Pencil size={16}/></button><button aria-label={`Удалить ${x.name}`} className="text-neutral-500 hover:text-brand" onClick={async()=>{if(confirmDel(x.name))try{await svc.deleteProduct(x.product_id);setErr('');s.reload()}catch(e){setErr((e as Error).message)}}}><Trash2 size={16}/></button></td></tr>)}</Table>
{ed&&<FormModal title={ed.id?'Редактировать товар':'Новый товар'} fields={fields} init={ed.init} onClose={()=>setEd(null)} onSubmit={async v=>{const d={name:v.name.trim(),description:v.description,price:+v.price,stock_quantity:+v.stock_quantity,category_id:+v.category_id};if(ed.id)await svc.updateProduct(ed.id,d);else await svc.createProduct(d);s.reload()}}/>}</>}}</Ready>}

export function AdminCategories(){const s=useData(svc.getCategories);const[ed,setEd]=useState<{id?:number;name:string}|null>(null);const[err,setErr]=useState('')
return <Ready s={s}>{c=><><Head title="Категории" action={<button className={btn.primary} onClick={()=>setEd({name:''})}><Plus size={16}/>Добавить</button>}/>{err&&<p role="alert" className="mb-3 rounded-lg bg-red-50 p-3 text-sm text-brand">{err}</p>}
<Table head={['ID','Категория','Товаров','Действия']}>{c.map(x=><tr key={x.category_id}><td className={td}>{x.category_id}</td><td className={`${td} font-medium`}>{x.category_name}</td><td className={td}>{x.count}</td><td className={td}><button aria-label={`Изменить ${x.category_name}`} className="mr-2 text-neutral-500 hover:text-brand" onClick={()=>setEd({id:x.category_id,name:x.category_name})}><Pencil size={16}/></button><button aria-label={`Удалить ${x.category_name}`} className="text-neutral-500 hover:text-brand" onClick={async()=>{if(confirmDel(x.category_name))try{await svc.deleteCategory(x.category_id);setErr('');s.reload()}catch(e){setErr((e as Error).message)}}}><Trash2 size={16}/></button></td></tr>)}</Table>
{ed&&<FormModal title={ed.id?'Редактировать категорию':'Новая категория'} fields={[{k:'name',label:'Название'}]} init={{name:ed.name}} onClose={()=>setEd(null)} onSubmit={async v=>{if(ed.id)await svc.updateCategory(ed.id,v.name);else await svc.createCategory(v.name);setErr('');s.reload()}}/>}</>}</Ready>}

const STATUSES:[string,string][]=[['Processing','В обработке'],['Shipped','В пути'],['Delivered','Доставлен'],['Cancelled','Отменён']]
export function AdminOrders(){const s=useData(svc.getOrders);const[view,setView]=useState<number|null>(null)
return <Ready s={s}>{o=>{const v=o.find(x=>x.order.order_id===view);return <><Head title="Заказы"/><Table head={['Заказ','Клиент','Дата','Статус','Сумма','Оплата','']}>{[...o].reverse().map(({order,user,payment})=><tr key={order.order_id}><td className={`${td} font-medium`}>#{order.order_id}</td><td className={td}>{user?.name}</td><td className={td}>{new Date(order.order_date).toLocaleDateString('ru-RU')}</td>
<td className={td}><select aria-label={`Статус заказа ${order.order_id}`} className="rounded-lg border border-neutral-300 px-2 py-1 text-sm" value={order.status} onChange={async e=>{await svc.updateOrderStatus(order.order_id,e.target.value);s.reload()}}>{STATUSES.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></td><td className={td}>{formatPrice(order.total_amount)}</td><td className={td}>{payment?.payment_method} · {payment?.status}</td><td className={td}><button aria-label={`Заказ ${order.order_id}`} className="text-neutral-500 hover:text-brand" onClick={()=>setView(order.order_id)}><Eye size={16}/></button></td></tr>)}</Table>
{v&&<Modal title={`Заказ #${v.order.order_id}`} onClose={()=>setView(null)}><div className="space-y-2 text-sm"><div>{v.user?.name} · {v.user?.phone}</div><div className="text-neutral-500">{v.user?.address}</div>{v.items.map(i=><div key={i.order_item_id} className="flex justify-between border-t border-neutral-100 pt-2"><span>{i.product?.name} × {i.quantity}</span><b>{formatPrice(i.unit_price*i.quantity)}</b></div>)}<div className="flex justify-between border-t border-neutral-200 pt-2 font-bold"><span>Итого</span><span>{formatPrice(v.order.total_amount)}</span></div></div></Modal>}</>}}</Ready>}

export function AdminUsers(){const s=useData(async()=>({u:await svc.getUsers(),o:await svc.getOrders(),r:await svc.getAllReviews()}));const[q,setQ]=useState('');const[view,setView]=useState<number|null>(null)
return <Ready s={s}>{({u,o,r})=>{const t=q.trim().toLowerCase();const list=u.filter(x=>!t||[x.name,x.email,x.phone].some(f=>f.toLowerCase().includes(t)));const v=u.find(x=>x.user_id===view)
return <><Head title="Пользователи"/><div className="relative mb-3 max-w-sm"><Search size={16} className="absolute left-3 top-3 text-neutral-400"/><input aria-label="Поиск пользователей" placeholder="Имя, email или телефон" value={q} onChange={e=>setQ(e.target.value)} className="h-10 w-full rounded-lg border border-neutral-300 bg-white pl-9 pr-3 text-sm outline-none focus:border-brand"/></div>
<Table head={['ID','Имя','Email','Телефон','Адрес','']}>{list.map(x=><tr key={x.user_id}><td className={td}>{x.user_id}</td><td className={`${td} font-medium`}>{x.name}</td><td className={td}>{x.email}</td><td className={`${td} whitespace-nowrap`}>{x.phone}</td><td className={td}>{x.address}</td><td className={td}><button aria-label={`Профиль ${x.name}`} className="text-neutral-500 hover:text-brand" onClick={()=>setView(x.user_id)}><Eye size={16}/></button></td></tr>)}</Table>
{v&&<Modal title={v.name} onClose={()=>setView(null)}><dl className="space-y-2 text-sm">{([['ID',v.user_id],['Email',v.email],['Телефон',v.phone],['Адрес',v.address??'—'],['Заказов',o.filter(x=>x.order.user_id===v.user_id).length],['Отзывов',r.filter(x=>x.user_id===v.user_id).length]] as [string,string|number][]).map(([k,val])=><div key={k} className="flex justify-between"><dt className="text-neutral-500">{k}</dt><dd className="font-medium">{val}</dd></div>)}</dl></Modal>}</>}}</Ready>}

export function AdminReviews(){const s=useData(async()=>({r:await svc.getAllReviews(),p:await svc.getProducts(),u:await svc.getUsers()}));const[f,setF]=useState({rating:'',product:'',user:''});const[view,setView]=useState<number|null>(null)
const sel='h-9 rounded-lg border border-neutral-300 bg-white px-2 text-sm'
return <Ready s={s}>{({r,p,u})=>{const list=r.filter(x=>(!f.rating||x.rating===+f.rating)&&(!f.product||x.product_id===+f.product)&&(!f.user||x.user_id===+f.user));const v=r.find(x=>x.review_id===view)
return <><Head title="Отзывы"/><div className="mb-3 flex flex-wrap gap-2"><select aria-label="Фильтр по оценке" className={sel} value={f.rating} onChange={e=>setF({...f,rating:e.target.value})}><option value="">Все оценки</option>{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} ★</option>)}</select>
<select aria-label="Фильтр по товару" className={`${sel} max-w-44`} value={f.product} onChange={e=>setF({...f,product:e.target.value})}><option value="">Все товары</option>{p.map(x=><option key={x.product_id} value={x.product_id}>{x.name}</option>)}</select>
<select aria-label="Фильтр по пользователю" className={`${sel} max-w-44`} value={f.user} onChange={e=>setF({...f,user:e.target.value})}><option value="">Все пользователи</option>{u.map(x=><option key={x.user_id} value={x.user_id}>{x.name}</option>)}</select></div>
<Table head={['ID','Пользователь','Товар','Оценка','Комментарий','Дата','']}>{list.map(x=><tr key={x.review_id}><td className={td}>{x.review_id}</td><td className={td}>{x.user?.name}</td><td className={td}>{x.product?.name}</td><td className={td}><Stars v={x.rating}/></td><td className={`${td} max-w-xs truncate`}>{x.comment}</td><td className={`${td} whitespace-nowrap`}>{new Date(x.review_date).toLocaleDateString('ru-RU')}</td><td className={`${td} whitespace-nowrap`}><button aria-label={`Просмотр отзыва ${x.review_id}`} className="mr-2 text-neutral-500 hover:text-brand" onClick={()=>setView(x.review_id)}><Eye size={16}/></button><button aria-label={`Удалить отзыв ${x.review_id}`} className="text-neutral-500 hover:text-brand" onClick={async()=>{if(confirmDel(`отзыв #${x.review_id}`)){await svc.deleteReview(x.review_id);s.reload()}}}><Trash2 size={16}/></button></td></tr>)}</Table>
{v&&<Modal title={`Отзыв #${v.review_id}`} onClose={()=>setView(null)}><div className="space-y-2 text-sm"><div><b>{v.user?.name}</b> о товаре <b>{v.product?.name}</b></div><Stars v={v.rating}/><p className="text-neutral-700">{v.comment}</p></div></Modal>}</>}}</Ready>}
