// Generates src/data/mock.ts from db/marketplace_db.sql (the single source of truth).
// Usage: npm run seed:generate   (then bump SEED_VERSION in src/data/store.ts)
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const sql = fs.readFileSync(path.join(root, 'db/marketplace_db.sql'), 'utf8')
    .split('\n').filter(l => !l.trim().startsWith('--')).join('\n')

// Parse one VALUES list "(a, 'b'), (c, 'd')" into arrays of JS values. Handles '' escapes.
function parseTuples(body) {
    const rows = []
    let i = 0
    const n = body.length
    while (i < n) {
        while (i < n && body[i] !== '(') i++
        if (i >= n) break
        i++
        const row = []
        for (;;) {
            while (/\s/.test(body[i])) i++
            if (body[i] === "'") {
                let s = ''
                i++
                for (;;) {
                    if (body[i] === "'" && body[i + 1] === "'") { s += "'"; i += 2 }
                    else if (body[i] === "'") { i++; break }
                    else s += body[i++]
                }
                row.push(s)
            } else {
                let t = ''
                while (body[i] !== ',' && body[i] !== ')') t += body[i++]
                t = t.trim()
                row.push(t.toUpperCase() === 'NULL' ? null : Number(t))
            }
            while (/\s/.test(body[i])) i++
            if (body[i] === ',') { i++; continue }
            if (body[i] === ')') { i++; break }
            throw new Error('Unexpected char in tuple: ' + body.slice(i, i + 30))
        }
        rows.push(row)
    }
    return rows
}

const tables = {}
for (const m of sql.matchAll(/INSERT\s+INTO\s+(\w+)\s*\(([^)]*)\)\s*VALUES([\s\S]*?);/gi)) {
    const cols = m[2].split(',').map(c => c.trim())
    const rows = parseTuples(m[3])
    rows.forEach(r => { if (r.length !== cols.length) throw new Error(`${m[1]}: ${r.length} values for ${cols.length} columns`) })
    tables[m[1]] = rows.map((r, k) => Object.fromEntries(cols.map((c, j) => [c, r[j]])))
}

// SERIAL primary keys are not in the INSERT column lists: ids are 1..n in insertion order.
const PK = { users: 'user_id', categories: 'category_id', products: 'product_id', orders: 'order_id', order_items: 'order_item_id', payments: 'payment_id', reviews: 'review_id' }
const ts = s => s.replace(' ', 'T') // '2026-08-05 15:00:00' -> ISO-like, parses in every browser
const out = {}
for (const [t, pk] of Object.entries(PK)) {
    if (!tables[t]) throw new Error('No INSERT found for ' + t)
    out[t] = tables[t].map((r, k) => {
        const row = { [pk]: k + 1, ...r }
        for (const f of ['order_date', 'payment_date', 'review_date']) if (f in row) row[f] = ts(row[f])
        return row
    })
}

const total = Object.values(out).reduce((a, r) => a + r.length, 0)
const lines = rows => '[\n' + rows.map(r => '  ' + JSON.stringify(r)).join(',\n') + ',\n]'
const file = `// GENERATED by scripts/generate-seed.mjs from db/marketplace_db.sql - DO NOT EDIT BY HAND.
// ${total} records. Timestamps are ISO-like local strings ('YYYY-MM-DDTHH:mm:ss'); DECIMAL columns are numbers.
import type {User,Category,Product,Order,OrderItem,Payment,Review} from '../types/database'
export const categories:Category[]=${lines(out.categories)}
export const users:User[]=${lines(out.users)}
export const products:Product[]=${lines(out.products)}
export const orders:Order[]=${lines(out.orders)}
export const orderItems:OrderItem[]=${lines(out.order_items)}
export const payments:Payment[]=${lines(out.payments)}
export const reviews:Review[]=${lines(out.reviews)}
`
fs.writeFileSync(path.join(root, 'src/data/mock.ts'), file)
console.log('mock.ts written:', Object.fromEntries(Object.entries(out).map(([t, r]) => [t, r.length])), 'total', total)
