import {useEffect,useMemo,useState} from 'react'
import {Link,Navigate,Route,Routes,useLocation,useNavigate,useParams,useSearchParams} from 'react-router-dom'
import {Trash2,ArrowRight,ChevronRight,SlidersHorizontal,ArrowUpDown,Check,CheckCircle2,CreditCard,Wallet,Banknote,Truck,ShoppingCart,Heart,User,Package,MessageSquare,Mail,Phone,MapPin,Star,Pencil,LogOut,type LucideIcon} from 'lucide-react'
import {useAuth} from './context/Auth'
import {Login,Register} from './pages/Auth'
import {AdminLayout,Dashboard,AdminProducts,AdminCategories,AdminOrders,AdminUsers,AdminReviews} from './pages/Admin'
import type {User as UserRow} from './types/database'
import {Breadcrumbs,Drawer,type Crumb} from './components/extra'
import {useStore} from './context/Store'
import * as svc from './services'
import {BottomNav,btn,catIcon,Container,EmptyState,ErrorState,Footer,formatPrice,Header,Img,LoadingState,Page,ProductGrid,Qty,StarRow,Stars,reviewsWord,useAsync} from './components/ui'
import type {ProductStats} from './services'

const statusCls:Record<string,string>={Delivered:'bg-green-100 text-green-700',Shipped:'bg-blue-100 text-blue-700',Processing:'bg-amber-100 text-amber-700',Cancelled:'bg-neutral-200 text-neutral-600'}
const statusRu:Record<string,string>={Delivered:'Доставлен',Shipped:'В пути',Processing:'В обработке',Cancelled:'Отменён'}
const fmtDate=(s:string)=>new Date(s).toLocaleDateString('ru-RU')
const Badge=({s}:{s:string})=><span className={`px-2.5 py-1 rounded-full text-xs font-medium ${statusCls[s]??'bg-neutral-100'}`}>{statusRu[s]??s}</span>
function Async<T>({s,children}:{s:{data?:T;error?:string;loading:boolean};children:(d:T)=>React.ReactNode}){return s.loading?<LoadingState/>:s.error?<ErrorState msg={s.error}/>:s.data===undefined?<EmptyState title="Не найдено"/>:<>{children(s.data)}</>}
const Section=({title,items,to='/search?q='}:{title:string;items:ProductStats[];to?:string})=><section className="mt-10"><div className="mb-4 flex items-end justify-between"><h2 className="text-xl font-bold tracking-tight md:text-2xl">{title}</h2><Link to={to} className="flex items-center gap-1 text-sm font-medium text-brand hover:underline">Все товары<ArrowRight size={14}/></Link></div><ProductGrid items={items}/></section>

function Home(){const s=useAsync(async()=>({p:await svc.getProducts(),c:await svc.getCategories()}),[])
return <main><Container className="py-5 md:py-8"><Async s={s}>{({p,c})=>{const hero=[...p].sort((a,b)=>b.price-a.price).slice(0,3)
return <>
<section className="grid overflow-hidden rounded-2xl border border-neutral-200 bg-white md:grid-cols-2">
<div className="flex flex-col justify-center p-6 md:p-12"><span className="mb-3 w-fit rounded bg-red-50 px-2 py-1 text-xs font-semibold text-brand">Доставка по всему Казахстану</span><h1 className="text-3xl font-extrabold leading-tight tracking-tight md:text-5xl">Всё нужное<br/>в одном месте</h1><p className="mt-3 max-w-md text-neutral-500">Техника, одежда, товары для дома и многое другое — по честным ценам.</p><Link to="/categories" className={`${btn.primary} mt-6 h-11 w-fit px-6`}>Начать покупки<ArrowRight size={16}/></Link></div>
<div className="relative hidden min-h-[320px] bg-gradient-to-br from-red-50 to-neutral-100 md:block">{hero.map((x,i)=><Link key={x.product_id} to={`/product/${x.product_id}`} className="absolute w-44 rounded-xl border border-neutral-200 bg-white p-2 shadow-lg transition hover:-translate-y-1" style={{left:`${8+i*26}%`,top:`${14+(i%2)*30}%`}}><Img id={x.product_id} alt={x.name} className="aspect-square w-full rounded-lg"/><div className="mt-2 truncate text-xs text-neutral-500">{x.name}</div><div className="text-sm font-bold">{formatPrice(x.price)}</div></Link>)}</div></section>
<nav aria-label="Категории" className="no-scrollbar -mx-4 mt-6 flex gap-2 overflow-x-auto px-4 md:mx-0 md:grid md:grid-cols-6 md:gap-3 md:px-0 lg:grid-cols-8">{c.filter(x=>x.count>0).slice(0,16).map(x=>{const I=catIcon(x.category_name);return <Link key={x.category_id} to={`/category/${x.category_id}`} className="flex min-w-24 flex-col items-center gap-2 rounded-xl border border-neutral-200 bg-white px-2 py-3 text-center text-xs font-medium transition hover:border-brand hover:text-brand"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-red-50 text-brand"><I size={20}/></span>{x.category_name}</Link>})}</nav>
<Section title="Популярные товары" items={[...p].sort((a,b)=>b.reviews-a.reviews).slice(0,5)}/>
<section className="mt-10 flex flex-col items-start justify-between gap-3 rounded-2xl bg-neutral-900 p-6 text-white md:flex-row md:items-center md:p-8"><div><h2 className="text-xl font-bold md:text-2xl">Спецпредложения недели</h2><p className="mt-1 text-sm text-neutral-300">Успейте купить — количество ограничено.</p></div><Link to="/search?q=" className={`${btn.primary} h-10 px-5`}>Смотреть<ChevronRight size={16}/></Link></section>
<Section title="Мало осталось" items={[...p].filter(x=>x.stock_quantity>0).sort((a,b)=>a.stock_quantity-b.stock_quantity).slice(0,5)}/>
<Section title="С высоким рейтингом" items={[...p].sort((a,b)=>b.rating-a.rating).slice(0,5)}/>
<Section title="Рекомендуем вам" items={[...p].reverse().slice(0,5)}/></>}}</Async></Container></main>}

function Categories(){const s=useAsync(svc.getCategories,[])
return <Page title="Категории"><Async s={s}>{c=><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{c.map(x=><Link key={x.category_id} to={`/category/${x.category_id}`} className="bg-white border border-neutral-200 rounded-xl p-6 shadow-sm hover:shadow-md"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-red-50 text-brand">{(()=>{const I=catIcon(x.category_name);return <I size={22}/>})()}</div><div className="font-semibold mt-3">{x.category_name}</div><div className="text-sm text-neutral-500">{x.count} товаров</div></Link>)}</div>}</Async></Page>}

const SORTS:[string,string][]=[['pop','Популярные'],['asc','Сначала дешевле'],['desc','Сначала дороже'],['rate','По рейтингу']]
const field='h-9 w-full rounded-lg border border-neutral-300 px-3 text-sm outline-none focus:border-brand'
function Catalog({items,title,crumbs}:{items:ProductStats[];title:string;crumbs:Crumb[]}){
const[min,setMin]=useState('');const[max,setMax]=useState('');const[rate,setRate]=useState(0);const[stock,setStock]=useState(false);const[sort,setSort]=useState('pop');const[open,setOpen]=useState<'f'|'s'|null>(null)
const list=useMemo(()=>items.filter(p=>(!min||p.price>=+min)&&(!max||p.price<=+max)&&p.rating>=rate&&(!stock||p.stock_quantity>0)).sort((a,b)=>sort==='asc'?a.price-b.price:sort==='desc'?b.price-a.price:sort==='rate'?b.rating-a.rating:b.reviews-a.reviews),[items,min,max,rate,stock,sort])
const fields=<div className="space-y-5"><div><h3 className="mb-2 text-sm font-semibold">Цена, ₸</h3><div className="flex gap-2"><input aria-label="Цена от" placeholder="от" type="number" className={field} value={min} onChange={e=>setMin(e.target.value)}/><input aria-label="Цена до" placeholder="до" type="number" className={field} value={max} onChange={e=>setMax(e.target.value)}/></div></div>
<div><h3 className="mb-2 text-sm font-semibold">Рейтинг</h3><div className="flex flex-wrap gap-2">{[0,3,4,4.5].map(r=><button key={r} aria-pressed={rate===r} onClick={()=>setRate(r)} className={`rounded-full border px-3 py-1 text-xs ${rate===r?'border-brand bg-red-50 text-brand':'border-neutral-300'}`}>{r?`от ${r}`:'Любой'}</button>)}</div></div>
<label className="flex items-center gap-2 text-sm"><input type="checkbox" className="accent-brand" checked={stock} onChange={e=>setStock(e.target.checked)}/>Только в наличии</label>
<button className={`${btn.secondary} w-full`} onClick={()=>{setMin('');setMax('');setRate(0);setStock(false)}}>Сбросить</button></div>
return <><Breadcrumbs items={crumbs}/><div className="mb-4 mt-2 flex flex-wrap items-baseline gap-x-3"><h1 className="text-2xl font-bold tracking-tight md:text-3xl">{title}</h1><span className="text-sm text-neutral-500">Найдено {list.length} товаров</span></div>
<div className="flex gap-6"><aside className="hidden w-60 shrink-0 md:block"><div className="sticky top-24 rounded-xl border border-neutral-200 bg-white p-4"><h2 className="mb-4 font-semibold">Фильтры</h2>{fields}</div></aside>
<div className="min-w-0 flex-1"><div className="mb-3 flex items-center"><div className="grid flex-1 grid-cols-2 gap-2 md:hidden"><button className={btn.secondary} onClick={()=>setOpen('f')}><SlidersHorizontal size={16}/>Фильтры</button><button className={btn.secondary} onClick={()=>setOpen('s')}><ArrowUpDown size={16}/>Сортировка</button></div>
<label className="ml-auto hidden items-center gap-2 text-sm text-neutral-500 md:flex">Сортировка<select className={`${field} w-auto`} value={sort} onChange={e=>setSort(e.target.value)}>{SORTS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>
{list.length?<ProductGrid items={list} cols="lg:grid-cols-3 xl:grid-cols-4"/>:<EmptyState title="Ничего не найдено" text="Измените фильтры или запрос." to="/categories" cta="К категориям"/>}</div></div>
<Drawer open={open==='f'} title="Фильтры" onClose={()=>setOpen(null)}>{fields}<button className={`${btn.primary} mt-5 w-full`} onClick={()=>setOpen(null)}>Показать {list.length} товаров</button></Drawer>
<Drawer open={open==='s'} title="Сортировка" onClose={()=>setOpen(null)}><div className="space-y-1">{SORTS.map(([v,l])=><button key={v} onClick={()=>{setSort(v);setOpen(null)}} className={`flex w-full items-center justify-between rounded-lg px-3 py-3 text-left text-sm ${sort===v?'bg-red-50 font-semibold text-brand':'hover:bg-neutral-50'}`}>{l}{sort===v&&<Check size={16}/>}</button>)}</div></Drawer></>}
function CategoryPage(){const id=+useParams().categoryId!;const s=useAsync(async()=>({c:await svc.getCategoryById(id),p:await svc.getProductsByCategory(id)}),[id])
return <Page><Async s={s}>{({c,p})=>c?<Catalog items={p} title={c.category_name} crumbs={[{label:'Главная',to:'/'},{label:'Категории',to:'/categories'},{label:c.category_name}]}/>:<EmptyState title="Категория не найдена" to="/categories" cta="К категориям"/>}</Async></Page>}
function Search(){const q=(useSearchParams()[0].get('q')??'').trim();const s=useAsync(()=>svc.getProducts(q),[q])
return <Page><Async s={s}>{p=><Catalog key={q} items={p} title={q?`По запросу «${q}»`:'Все товары'} crumbs={[{label:'Главная',to:'/'},{label:'Поиск'}]}/>}</Async></Page>}

function ReviewForm({productId,onDone}:{productId:number;onDone:()=>void}){const{session}=useAuth();const[rating,setRating]=useState(5);const[text,setText]=useState('')
if(!session)return <p className="mt-4 rounded-lg bg-neutral-50 p-3 text-sm text-neutral-600">Пожалуйста, войдите, чтобы оставить отзыв. <Link to="/login" className="font-medium text-brand">Войти</Link></p>
if(session.role==='admin')return null
return <form className="mt-4 rounded-lg border border-neutral-200 p-4" onSubmit={async e=>{e.preventDefault();await svc.createReview({user_id:session.user_id,product_id:productId,rating,comment:text.trim()});setText('');onDone()}}><h3 className="mb-2 text-sm font-semibold">Написать отзыв</h3><div className="mb-2 flex gap-1" role="radiogroup" aria-label="Оценка">{[1,2,3,4,5].map(n=><button type="button" key={n} role="radio" aria-checked={rating===n} aria-label={`${n} из 5`} onClick={()=>setRating(n)}><Star size={22} className={n<=rating?'fill-amber-400 text-amber-400':'text-neutral-300'}/></button>)}</div><textarea required aria-label="Комментарий" rows={3} value={text} onChange={e=>setText(e.target.value)} placeholder="Ваш отзыв" className="w-full rounded-lg border border-neutral-300 p-2 text-sm outline-none focus:border-brand"/><button className={`${btn.primary} mt-2`}>Отправить отзыв</button></form>}
function EditProfile({u,onSaved}:{u:UserRow;onSaved:()=>void}){const[open,setOpen]=useState(false);const[f,setF]=useState({name:u.name,phone:u.phone,address:u.address??''});const[err,setErr]=useState('');const L={name:'Имя',phone:'Телефон',address:'Адрес'}
if(!open)return <button className={`${btn.secondary} mt-4`} onClick={()=>setOpen(true)}><Pencil size={14}/>Редактировать профиль</button>
return <form className="mt-4 space-y-3 border-t border-neutral-100 pt-4" onSubmit={async e=>{e.preventDefault();if(!f.name.trim()||!f.phone.trim()){setErr('Имя и телефон обязательны');return}await svc.updateUser(u.user_id,{name:f.name.trim(),phone:f.phone.trim(),address:f.address.trim()||null});setOpen(false);onSaved()}}>{(['name','phone','address'] as const).map(k=><label key={k} className="block text-sm"><span className="mb-1 block text-neutral-600">{L[k]}</span><input className={field} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}{err&&<p role="alert" className="text-sm text-brand">{err}</p>}<div className="flex gap-2"><button className={btn.primary}>Сохранить</button><button type="button" className={btn.secondary} onClick={()=>setOpen(false)}>Отмена</button></div></form>}
function RequireAuth({admin,children}:{admin?:boolean;children:React.ReactNode}){const{session}=useAuth();const loc=useLocation()
return !session?<Navigate to="/login" state={{from:loc.pathname}} replace/>:admin&&session.role!=='admin'?<Navigate to="/" replace/>:<>{children}</>}
const Distribution=({r}:{r:{rating:number}[]})=>{const avg=r.length?r.reduce((a,x)=>a+x.rating,0)/r.length:0
return <div className="flex items-center gap-6"><div className="text-center"><div className="text-4xl font-extrabold">{avg?avg.toFixed(1):'—'}</div><div className="mt-1"><StarRow v={avg} size={18}/></div><div className="mt-1 text-xs text-neutral-500">{reviewsWord(r.length)}</div></div>
<div className="flex-1 space-y-1.5">{[5,4,3,2,1].map(n=>{const c=r.filter(x=>x.rating===n).length;const pc=r.length?Math.round(c*100/r.length):0
return <div key={n} className="flex items-center gap-2 text-xs"><span className="w-8 text-neutral-600">{n} ★</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-neutral-100"><div className="h-full bg-amber-400" style={{width:`${pc}%`}}/></div><span className="w-9 text-right text-neutral-500">{c}</span></div>})}</div></div>}
const Card=({title,children}:{title:string;children:React.ReactNode})=><section className="rounded-xl border border-neutral-200 bg-white p-5"><h2 className="mb-4 text-lg font-bold">{title}</h2>{children}</section>
function ProductPage(){const id=+useParams().productId!;const{add,favs,toggleFav}=useStore();const nav=useNavigate();const[q,setQ]=useState(1);const[ver,setVer]=useState(0)
const s=useAsync(async()=>{const p=await svc.getProductById(id);if(!p)return null;const[c,r,rel]=await Promise.all([svc.getCategoryById(p.category_id),svc.getReviewsByProductId(id),svc.getProductsByCategory(p.category_id)]);return{p,c,r,rel:rel.filter(x=>x.product_id!==id).slice(0,5)}},[id,ver])
return <Page><Async s={s}>{d=>{if(!d)return <EmptyState title="Товар недоступен" text="Возможно, он был удалён." to="/categories" cta="К категориям"/>
const{p,c,r,rel}=d;const fav=favs.includes(id);const ok=p.stock_quantity>0
return <><Breadcrumbs items={[{label:'Главная',to:'/'},{label:'Категории',to:'/categories'},{label:c?.category_name??'',to:`/category/${p.category_id}`},{label:p.name}]}/>
<div className="mt-4 grid gap-6 lg:grid-cols-2"><div className="rounded-xl border border-neutral-200 bg-white"><Img id={id} alt={p.name} className="aspect-square w-full"/></div>
<div className="rounded-xl border border-neutral-200 bg-white p-5 md:p-6"><h1 className="text-2xl font-bold tracking-tight md:text-3xl">{p.name}</h1>
<div className="mt-2 flex items-center gap-3 text-sm text-neutral-500"><Stars v={p.rating}/><a href="#reviews" className="hover:text-brand">{reviewsWord(p.reviews)}</a><span>Артикул {p.product_id}</span></div>
<div className="mt-5 text-4xl font-extrabold tracking-tight">{formatPrice(p.price)}</div>
<div className={`mt-2 text-sm font-medium ${ok?'text-emerald-600':'text-neutral-500'}`}>{ok?`В наличии · ${p.stock_quantity} шт.`:'Нет в наличии'}</div>
{ok&&<div className="mt-3 flex items-center gap-2 rounded-lg bg-neutral-50 p-3 text-sm"><Truck size={18} className="text-brand"/>Доставка завтра · бесплатно по Алматы</div>}
{ok&&<div className="mt-5 flex flex-wrap items-center gap-3"><Qty v={q} max={p.stock_quantity} on={setQ}/><button className={`${btn.primary} h-10 flex-1 px-6`} onClick={()=>add(id,p.stock_quantity,q)}><ShoppingCart size={16}/>Добавить в корзину</button></div>}
<div className="mt-3 flex gap-3">{ok&&<button className={`${btn.secondary} h-10 flex-1`} onClick={()=>{add(id,p.stock_quantity,q);nav('/checkout')}}>Купить сейчас</button>}<button aria-pressed={fav} className={`${btn.secondary} h-10 ${ok?'':'flex-1'}`} onClick={()=>toggleFav(id)}><Heart size={16} className={fav?'fill-brand text-brand':''}/>{fav?'В избранном':'В избранное'}</button></div></div></div>
<div className="mt-6 grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><Card title="Описание"><p className="text-neutral-700">{p.description}</p></Card>
<Card title="Характеристики"><dl className="divide-y divide-neutral-100 text-sm">{[['Категория',c?.category_name],['Артикул',`#${p.product_id}`],['Наличие',ok?`${p.stock_quantity} шт.`:'Нет в наличии'],['Цена',formatPrice(p.price)]].map(([k,v])=><div key={k} className="flex justify-between py-2.5"><dt className="text-neutral-500">{k}</dt><dd className="font-medium">{v}</dd></div>)}</dl></Card></div>
<div id="reviews" className="scroll-mt-24"><Card title="Отзывы покупателей"><Distribution r={r}/><ReviewForm productId={id} onDone={()=>setVer(v=>v+1)}/><div className="mt-5 space-y-4 border-t border-neutral-100 pt-4">{r.length?r.map(x=><div key={x.review_id} className="flex gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-red-50 text-sm font-semibold text-brand">{x.user?.name[0]}</span><div><div className="flex items-center gap-2 text-sm"><b>{x.user?.name}</b><span className="text-xs text-neutral-400">{longDate(x.review_date)}</span></div><StarRow v={x.rating} size={14}/><p className="mt-1 text-sm text-neutral-700">{x.comment}</p></div></div>):<p className="text-sm text-neutral-500">Отзывов пока нет.</p>}</div></Card></div></div>
{rel.length>0&&<section className="mt-10"><h2 className="mb-4 text-xl font-bold tracking-tight md:text-2xl">Похожие товары</h2><ProductGrid items={rel}/></section>}
{ok&&<div className="h-14 md:hidden"/>}{ok&&<div className="fixed inset-x-0 bottom-[52px] z-20 flex items-center gap-3 border-t border-neutral-200 bg-white px-4 py-2 md:hidden"><div className="text-lg font-bold">{formatPrice(p.price*q)}</div><button className={`${btn.primary} ml-auto h-10 flex-1`} onClick={()=>add(id,p.stock_quantity,q)}>В корзину</button></div>}</>}}</Async></Page>}

function useCartItems(){const{cart}=useStore();return useAsync(async()=>Promise.all(Object.entries(cart).map(async([id,qty])=>({p:await svc.getProductById(+id),qty}))).then(x=>x.filter(i=>i.p).map(i=>({p:i.p as ProductStats,qty:Math.min(i.qty,(i.p as ProductStats).stock_quantity)}))),[JSON.stringify(cart)])}
const Cart=()=>{const{setQty,remove}=useStore();const s=useCartItems()
return <Page title="Корзина"><Async s={s}>{items=>{const total=items.reduce((a,i)=>a+i.p.price*i.qty,0)
return items.length?<div className="grid lg:grid-cols-3 gap-6"><div className="lg:col-span-2 space-y-3">{items.map(({p,qty})=><div key={p.product_id} className="bg-white border border-neutral-200 rounded-xl p-3 shadow-sm flex gap-4 items-center"><Img id={p.product_id} alt={p.name} className="w-20 h-20 rounded-xl"/>
<div className="flex-1"><Link to={`/product/${p.product_id}`} className="font-medium">{p.name}</Link><div className="text-sm text-neutral-500">{formatPrice(p.price)}</div><div className="mt-2"><Qty v={qty} max={p.stock_quantity} on={n=>setQty(p.product_id,n)}/></div></div>
<div className="text-right font-bold text-brand">{formatPrice(p.price*qty)}</div><button aria-label="Удалить" onClick={()=>remove(p.product_id)}><Trash2 size={18} className="text-neutral-400 hover:text-brand"/></button></div>)}</div>
<div className="bg-white border border-neutral-200 rounded-xl p-5 shadow-sm h-fit"><div className="flex justify-between text-lg font-bold"><span>Итого:</span><span>{formatPrice(total)}</span></div><Link to="/checkout" className="block text-center mt-4 bg-brand text-white py-3 rounded-xl font-medium">Оформить заказ</Link></div></div>
:<EmptyState title="В корзине пока пусто" text="Добавьте товары, чтобы оформить заказ."/>}}</Async></Page>}

const longDate=(s:string)=>new Date(s).toLocaleDateString('ru-RU',{day:'numeric',month:'long',year:'numeric'})
const payRu:Record<string,string>={'Bank Card':'Банковская карта','Kaspi Pay':'Kaspi Pay','Cash on delivery':'Наличными при получении'}
const PAY:[string,string,LucideIcon][]=[['card','Банковская карта',CreditCard],['kaspi','Kaspi Pay',Wallet],['cash','Наличными при получении',Banknote]]
const Box=({n,title,children}:{n:number;title:string;children:React.ReactNode})=><section className="rounded-xl border border-neutral-200 bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-semibold"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-brand text-xs text-white">{n}</span>{title}</h2>{children}</section>
function Checkout(){const sess=useAuth().session;const uid=sess?.user_id??0;const{clear}=useStore();const s=useCartItems();const u=useAsync(()=>svc.getUserById(uid),[]);const[done,setDone]=useState<number|null>(null)
const[f,setF]=useState({name:'',phone:'',city:'Алматы',address:'',pay:'card'})
useEffect(()=>{const d=u.data;if(d)setF(x=>({...x,name:d.name,phone:d.phone,address:d.address??''}))},[u.data])
const inp=(label:string,k:'name'|'phone'|'city'|'address',type='text')=><label className="block text-sm"><span className="mb-1 block text-neutral-600">{label}</span><input required type={type} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})} className={field}/></label>
const steps=['Получатель','Доставка','Оплата','Подтверждение'];const ok=[!!(f.name&&f.phone),!!(f.city&&f.address),true,false];const cur=ok.indexOf(false)
if(sess?.role==='admin')return <Page><EmptyState title="Оформление заказов недоступно администратору" text="Войдите как покупатель, чтобы сделать заказ." to="/admin" cta="В админ-панель"/></Page>
if(done)return <Page><div className="mx-auto max-w-md rounded-xl border border-neutral-200 bg-white p-8 text-center"><CheckCircle2 size={56} className="mx-auto text-emerald-500"/><h1 className="mt-4 text-2xl font-bold">Заказ успешно оформлен!</h1><p className="mt-2 text-lg">Номер заказа: #{done}</p><p className="mt-1 text-sm text-neutral-500">Мы свяжемся с вами для подтверждения доставки.</p><div className="mt-6 flex justify-center gap-2"><Link to="/orders" className={btn.primary}>Мои заказы</Link><Link to="/" className={btn.secondary}>На главную</Link></div></div></Page>
return <Page><Breadcrumbs items={[{label:'Главная',to:'/'},{label:'Корзина',to:'/cart'},{label:'Оформление заказа'}]}/><h1 className="mb-4 mt-2 text-2xl font-bold tracking-tight md:text-3xl">Оформление заказа</h1>
<ol className="mb-6 grid grid-cols-4 gap-2">{steps.map((t,i)=><li key={t} className="flex flex-col items-center gap-1.5 text-center text-xs md:flex-row md:justify-center md:gap-2 md:text-sm"><span className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-semibold ${ok[i]?'bg-brand text-white':i===cur?'border-2 border-brand text-brand':'bg-neutral-200 text-neutral-500'}`}>{ok[i]?<Check size={14}/>:i+1}</span><span className={i<=cur?'font-medium':'text-neutral-400'}>{t}</span></li>)}</ol>
<Async s={s}>{items=>{const total=items.reduce((a,i)=>a+i.p.price*i.qty,0)
return items.length?<form onSubmit={e=>{e.preventDefault();setDone(svc.createOrder(uid,items.map(i=>({product_id:i.p.product_id,quantity:i.qty,unit_price:i.p.price})),f.pay));clear()}} className="grid items-start gap-6 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2">
<Box n={1} title="Получатель"><div className="grid gap-3 sm:grid-cols-2">{inp('Имя','name')}{inp('Телефон','phone','tel')}</div></Box>
<Box n={2} title="Доставка"><div className="grid gap-3 sm:grid-cols-2">{inp('Город','city')}{inp('Адрес','address')}</div></Box>
<Box n={3} title="Оплата"><div className="grid gap-2 sm:grid-cols-3">{PAY.map(([v,l,I])=><label key={v} className={`flex cursor-pointer items-center gap-2 rounded-lg border p-3 text-sm ${f.pay===v?'border-brand bg-red-50':'border-neutral-300'}`}><input type="radio" name="pay" className="accent-brand" checked={f.pay===v} onChange={()=>setF({...f,pay:v})}/><I size={16}/>{l}</label>)}</div></Box></div>
<aside className="rounded-xl border border-neutral-200 bg-white p-5 lg:sticky lg:top-24"><h2 className="mb-3 font-semibold">Ваш заказ</h2><div className="divide-y divide-neutral-100">{items.map(i=><div key={i.p.product_id} className="flex items-center gap-3 py-2"><Img id={i.p.product_id} alt={i.p.name} className="h-12 w-12 shrink-0 rounded-lg border border-neutral-100"/><div className="min-w-0 flex-1 text-sm"><div className="truncate">{i.p.name}</div><div className="text-xs text-neutral-500">{i.qty} × {formatPrice(i.p.price)}</div></div></div>)}</div>
<dl className="mt-3 space-y-1 border-t border-neutral-100 pt-3 text-sm"><div className="flex justify-between"><dt className="text-neutral-500">Товары</dt><dd>{formatPrice(total)}</dd></div><div className="flex justify-between"><dt className="text-neutral-500">Доставка</dt><dd className="text-emerald-600">Бесплатно</dd></div><div className="flex justify-between pt-2 text-lg font-bold"><dt>Итого</dt><dd>{formatPrice(total)}</dd></div></dl>
<button className={`${btn.primary} mt-4 h-11 w-full`}>Подтвердить заказ</button></aside></form>:<EmptyState title="В корзине пока пусто" text="Добавьте товары, чтобы оформить заказ."/>}}</Async></Page>}

function Orders(){const uid=useAuth().session?.user_id??0;const s=useAsync(async()=>Promise.all((await svc.getOrdersByUserId(uid)).map(async o=>({...o,payment:await svc.getPaymentByOrderId(o.order_id)}))),[])
return <Page><h1 className="mb-5 text-2xl font-bold tracking-tight md:text-3xl">Мои заказы</h1><Async s={s}>{o=>o.length?<div className="space-y-4">{[...o].reverse().map(x=><article key={x.order_id} className="overflow-hidden rounded-xl border border-neutral-200 bg-white">
<header className="flex flex-wrap items-center justify-between gap-2 border-b border-neutral-100 bg-neutral-50 px-4 py-3"><div><b>Заказ #{x.order_id}</b><span className="ml-3 text-sm text-neutral-500">{longDate(x.order_date)}</span></div><Badge s={x.status}/></header>
<div className="divide-y divide-neutral-100 px-4">{x.items.map(i=><div key={i.order_item_id} className="flex items-center gap-3 py-3"><Img id={i.product_id} alt={i.product?.name??''} className="h-16 w-16 shrink-0 rounded-lg border border-neutral-100"/><div className="min-w-0 flex-1"><Link to={`/product/${i.product_id}`} className="line-clamp-2 text-sm hover:text-brand">{i.product?.name}</Link><div className="text-xs text-neutral-500">{i.quantity} × {formatPrice(i.unit_price)}</div></div></div>)}</div>
<footer className="flex flex-wrap items-center justify-between gap-3 border-t border-neutral-100 px-4 py-3"><div className="text-xs text-neutral-500">{payRu[x.payment?.payment_method??'']??'—'} · {x.payment?.status==='Paid'?'Оплачен':'Ожидает оплаты'}</div><div className="flex items-center gap-4"><div className="text-lg font-bold">{formatPrice(x.total_amount)}</div><Link to={`/orders/${x.order_id}`} className={btn.secondary}>Подробнее</Link></div></footer></article>)}</div>:<EmptyState title="Заказов пока нет" text="Оформите первый заказ."/>}</Async></Page>}

function OrderDetails(){const id=+useParams().orderId!;const{session}=useAuth();const uid=session?.user_id??0;const s=useAsync(()=>svc.getOrderById(id),[id])
return <Page><Async s={s}>{({order,items,payment,user})=>{if(order.user_id!==uid&&session?.role!=='admin')return <EmptyState title="Заказ не найден" to="/orders" cta="Мои заказы"/>;const n=1+(payment?.status==='Paid'?1:0)+(order.status==='Shipped'||order.status==='Delivered'?1:0)+(order.status==='Delivered'?1:0)
const steps=['Заказ оформлен','Оплачен','Передан в доставку','Доставлен']
return <><Breadcrumbs items={[{label:'Главная',to:'/'},{label:'Заказы',to:'/orders'},{label:`Заказ #${order.order_id}`}]}/>
<div className="mb-4 mt-2 flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold tracking-tight md:text-3xl">Заказ #{order.order_id}</h1><Badge s={order.status}/><span className="text-sm text-neutral-500">{longDate(order.order_date)}</span></div>
<ol className="mb-6 grid grid-cols-4 rounded-xl border border-neutral-200 bg-white p-4">{steps.map((t,i)=><li key={t} className="text-center"><div className="flex items-center"><span className={`h-0.5 flex-1 ${i>0&&i<n?'bg-brand':i>0?'bg-neutral-200':''}`}/><span className={`flex h-7 w-7 items-center justify-center rounded-full ${i<n?'bg-brand text-white':'bg-neutral-200 text-neutral-400'}`}><Check size={14}/></span><span className={`h-0.5 flex-1 ${i<3?(i+1<n?'bg-brand':'bg-neutral-200'):''}`}/></div><div className={`mt-2 text-[11px] leading-tight md:text-sm ${i<n?'font-medium':'text-neutral-400'}`}>{t}</div></li>)}</ol>
<div className="grid items-start gap-6 lg:grid-cols-3"><section className="rounded-xl border border-neutral-200 bg-white p-5 lg:col-span-2"><h2 className="mb-2 font-semibold">Товары</h2><div className="divide-y divide-neutral-100">{items.map(i=><div key={i.order_item_id} className="flex items-center gap-3 py-3"><Img id={i.product_id} alt={i.product?.name??''} className="h-16 w-16 shrink-0 rounded-lg border border-neutral-100"/><div className="min-w-0 flex-1"><Link to={`/product/${i.product_id}`} className="line-clamp-2 text-sm hover:text-brand">{i.product?.name}</Link><div className="text-xs text-neutral-500">{i.quantity} × {formatPrice(i.unit_price)}</div></div><b className="text-sm">{formatPrice(i.unit_price*i.quantity)}</b></div>)}</div></section>
<aside className="space-y-4"><section className="rounded-xl border border-neutral-200 bg-white p-5 text-sm"><h2 className="mb-2 font-semibold">Доставка</h2><div>{user?.name}</div><div className="text-neutral-500">{user?.phone}</div><div className="text-neutral-500">{user?.address}</div></section>
<section className="rounded-xl border border-neutral-200 bg-white p-5 text-sm"><h2 className="mb-2 font-semibold">Оплата</h2><div>{payRu[payment?.payment_method??'']??'—'}</div><div className="text-neutral-500">{payment?.status==='Paid'?'Оплачен':'Ожидает оплаты'}{payment&&` · ${longDate(payment.payment_date)}`}</div></section>
<section className="rounded-xl border border-neutral-200 bg-white p-5"><div className="flex justify-between text-lg font-bold"><span>Итого</span><span>{formatPrice(order.total_amount)}</span></div></section></aside></div></>}}</Async></Page>}

function Favorites(){const{favs}=useStore();const s=useAsync(async()=>(await svc.getProducts()).filter(p=>favs.includes(p.product_id)),[favs.join()])
return <Page><div className="mb-5 flex items-baseline gap-3"><h1 className="text-2xl font-bold tracking-tight md:text-3xl">Избранное</h1><span className="text-sm text-neutral-500">{favs.length} товаров</span></div><Async s={s}>{p=>p.length?<ProductGrid items={p}/>:<EmptyState title="В избранном пока ничего нет" text="Добавляйте товары, которые хотите сохранить."/>}</Async></Page>}

function Profile(){const{session,logout}=useAuth();const nav=useNavigate();const out=<button onClick={()=>{logout();nav('/')}} className={`${btn.secondary} shrink-0 whitespace-nowrap`}><LogOut size={16}/>Выйти</button>;const uid=session?.user_id??0;const[ver,setVer]=useState(0);const tab=useSearchParams()[0].get('tab')==='reviews'?'reviews':'info';const s=useAsync(async()=>({u:await svc.getUserById(uid),r:await svc.getReviewsByUserId(uid)}),[ver])
const links:[string,string,LucideIcon,boolean][]=[['Профиль','/profile',User,tab==='info'],['Мои заказы','/orders',Package,false],['Избранное','/favorites',Heart,false],['Мои отзывы','/profile?tab=reviews',MessageSquare,tab==='reviews']]
if(session?.role==='admin')return <Page><h1 className="mb-5 text-2xl font-bold tracking-tight md:text-3xl">Профиль администратора</h1><div className="rounded-xl border border-neutral-200 bg-white p-5"><p className="font-medium">{session.email}</p><p className="text-sm text-neutral-500">Демо-аккаунт администратора</p><div className="mt-4 flex gap-2"><Link to="/admin" className={btn.primary}>Открыть админ-панель</Link>{out}</div></div></Page>
return <Page><h1 className="mb-5 text-2xl font-bold tracking-tight md:text-3xl">Личный кабинет</h1><div className="grid items-start gap-6 md:grid-cols-[220px_1fr]">
<nav aria-label="Разделы профиля" className="no-scrollbar -mx-4 flex gap-2 overflow-x-auto px-4 md:mx-0 md:flex-col md:gap-1 md:rounded-xl md:border md:border-neutral-200 md:bg-white md:p-2">{links.map(([l,to,I,a])=><Link key={l} to={to} className={`flex shrink-0 items-center gap-2 whitespace-nowrap rounded-lg border px-3 py-2 text-sm md:border-0 ${a?'border-brand bg-red-50 font-semibold text-brand':'border-neutral-200 bg-white hover:bg-neutral-50 md:bg-transparent'}`}><I size={16}/>{l}</Link>)}{out}</nav>
<Async s={s}>{({u,r})=>u?tab==='info'?<section className="rounded-xl border border-neutral-200 bg-white p-5 md:p-6"><div className="flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-brand text-xl font-bold text-white">{u.name[0]}</span><div><h2 className="text-xl font-bold">{u.name}</h2><p className="text-sm text-neutral-500">Покупатель MarketKZ</p></div></div>
<dl className="mt-5 divide-y divide-neutral-100 text-sm">{([['Email',u.email,Mail],['Телефон',u.phone,Phone],['Адрес',u.address??'—',MapPin]] as [string,string,LucideIcon][]).map(([k,v,I])=><div key={k} className="flex items-center gap-3 py-3"><I size={18} className="text-neutral-400"/><dt className="w-24 text-neutral-500">{k}</dt><dd className="font-medium">{v}</dd></div>)}</dl><EditProfile u={u} onSaved={()=>setVer(v=>v+1)}/></section>
:<section className="rounded-xl border border-neutral-200 bg-white p-5"><h2 className="mb-3 font-semibold">Мои отзывы</h2>{r.length?<div className="divide-y divide-neutral-100">{r.map(x=><div key={x.review_id} className="py-3 text-sm"><div className="flex items-center gap-3"><Link to={`/product/${x.product_id}`} className="font-medium hover:text-brand">{x.product?.name}</Link><Stars v={x.rating}/><span className="text-xs text-neutral-400">{longDate(x.review_date)}</span></div><p className="mt-1 text-neutral-700">{x.comment}</p></div>)}</div>:<p className="text-sm text-neutral-500">Вы ещё не оставляли отзывы.</p>}</section>:<EmptyState title="Пользователь не найден"/>}</Async></div></Page>}

export default function App(){const admin=useLocation().pathname.startsWith('/admin')
return <>{!admin&&<Header/>}<div className="min-h-[60vh]"><Routes>
<Route path="/" element={<Home/>}/><Route path="/categories" element={<Categories/>}/><Route path="/category/:categoryId" element={<CategoryPage/>}/><Route path="/search" element={<Search/>}/>
<Route path="/product/:productId" element={<ProductPage/>}/><Route path="/cart" element={<Cart/>}/><Route path="/checkout" element={<RequireAuth><Checkout/></RequireAuth>}/>
<Route path="/orders" element={<RequireAuth><Orders/></RequireAuth>}/><Route path="/orders/:orderId" element={<RequireAuth><OrderDetails/></RequireAuth>}/><Route path="/favorites" element={<Favorites/>}/><Route path="/profile" element={<RequireAuth><Profile/></RequireAuth>}/>
<Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/>
<Route path="/admin" element={<RequireAuth admin><AdminLayout/></RequireAuth>}><Route index element={<Dashboard/>}/><Route path="products" element={<AdminProducts/>}/><Route path="categories" element={<AdminCategories/>}/><Route path="orders" element={<AdminOrders/>}/><Route path="users" element={<AdminUsers/>}/><Route path="reviews" element={<AdminReviews/>}/></Route>
<Route path="*" element={<Page><EmptyState title="Страница не найдена"/></Page>}/></Routes></div>{!admin&&<><Footer/><BottomNav/></>}</>}
